### ISSUE TITLE
Allow scrapers to pass org names into bill.add_action ?

### ISSUE THREAD

**Issue by twneale** [opencivicdata/pupa#105]
Talking with @jamesturk It'd be nice to be able to pass an org name or org instance to add_action, which would require some tinkering with add_action.

**Comment by jpmckinney** [comment]
See #233 for a solution to copy

**Comment by fgregg** [comment]
Isn't this already implemented: https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/bill.py#L50

Here's how I do it: https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/bills.py#L81

**Comment by jpmckinney** [comment]
Very good!
