### ISSUE TITLE
upgrade guide

### ISSUE THREAD

**Issue by paultag** [opencivicdata/pupa#139]
Keep a rolling docs page when we do updates. Start for 0.3 -> 0.4:

https://github.com/opencivicdata/pupa/issues/124

**Comment by jpmckinney** [comment]
Upgrade docs will be relevant to 0.5 :) @jamesturk

**Comment by jamesturk** [comment]
yes they will, Vote->VoteEvent is a big one and database migration is going to be fun

hoping 0.5 gets pretty close to 1.0 in terms of API stability

**Comment by jamesturk** [comment]
if someone has a fairly complete pupa 0.4 db they could dump and give to me that'd be great actually, the database migration is outside the bounds of what Django can do so it is going to need to be a special one-off script 'migrate_ocd_db.py'

**Comment by jpmckinney** [comment]
My DB has mostly people, memberships, posts, organizations, contact details, but I have one jurisdiction with bills, votes. How should I transfer it?

**Comment by jpmckinney** [comment]
Hmm, well if anyone is still on 0.4 they are very quiet about it. I'm logging new backwards-incompatible changes in the changelog.
