### ISSUE TITLE
[discussion] Switching to Scrapy / Spliting the repo

### ISSUE THREAD

**Issue by Vanuan** [opencivicdata/pupa#144]
[Scrapy](http://scrapy.org/) seems to be more developed and feature rich project. Have you ever considered switching to it from [scrapelib](https://github.com/sunlightlabs/scrapelib/)?

One thing that I don't like about pupa is that it contains both scrapers and importers, enforcing the need of django, etc.

I would like to write my own scrapy scrapers, scrape it to database (or csv or json) independently (using scrapyd or a [hosted service](http://scrapinghub.com/clients/)) but leverage the ability to validate and dedupe data using pupa's functionality. And then separately exporting/importing/converting between different formats and serving via API.

Does anybody have any similar thoughts?

**Comment by fgregg** [comment]
So you just want Pupas validators but none of the other bits? What's your use case?

**Comment by paultag** [comment]
@Vanuan the Django bits only get imported if you're running the import stage. There's no Django requirement if you just `--scrape` -- which is to say it's not a hard requirement.

It sounds like you just want to use `--scrape` -- but the import / Django models are really useful for storing it to a database -- and it makes writing a front-end easier.

As for Scrapy, yeah, I've taken a look at it, but we handle a bunch of edge cases we hit in Government websites with a bit more grace -- I'm a fan of Scrapy, but I'm not super interested in porting it right now.

If you really want it, we can see what extension points we can make to it happen. I'm going to close this issue, let's open up issues for specific integration issues that you might have :)

**Comment by Vanuan** [comment]
>  There's no Django requirement if you just --scrape -- which is to say it's not a hard requirement.

You can't (easily) use `--scrape` without installing django. There is requirements.txt file.

> So you just want Pupas validators but none of the other bits? What's your use case?

I want to write my scrapers using scrapy, and then the results to be picked up by pupa. And vice versa: run pupa scrapers and use something else to run API.
