### ISSUE TITLE
Pupa should link Person to Vote

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/pupa#147]
The `Vote` class' `yes`, `no`, `other` and `vote` helpers don't make the link to the Person by setting the `voter` field.

**Comment by fgregg** [comment]
:+1:  We need this too!

**Comment by jpmckinney** [comment]
I'm going to fix #148 first, because doing vote logic when the code calls two different things "votes" is confusing as hell.

**Comment by fgregg** [comment]
Word!
