### ISSUE TITLE
Double back to ensure pseudo IDs are handled

### ISSUE THREAD

**Issue by paultag** [opencivicdata/pupa#162]
The recent changesets in #160 and #161 lead me to think that we have other `*_id` fields that won't take a pseudo ID. All the more reason to *only* use the scrape-time helpers, and never use `make_pseudo_id` in the scraper.

**Comment by fgregg** [comment]
Are you saying that we shouldn't use make_pseudo_id in the scrapers?  Definitely agree.

**Comment by paultag** [comment]
No, `make_pseudo_id` should not be used in scrapers, if you need it, it likely needs a full blown helper method.

**Comment by jamesturk** [comment]
Yep.  Should probably clarify it is an internal API, will probably rename to _make_psuedo_id to hint at this.
