### ISSUE TITLE
Add ability to add object (a Person, Organization, etc) to an event

### ISSUE THREAD

**Issue by AshleyTemple** [opencivicdata/pupa#166]
At present you can hack it in by appending the dict representation to Event.participants, but you should be able to add_participant(some_organization) or add_participant(some_person).

**Comment by fgregg** [comment]
I think this is implemented 

https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/event.py#L25 

and 

https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/event.py#L31

**Comment by jamesturk** [comment]
yep, this looks like it's there. going to close this one
