### ISSUE TITLE
Add test case to verify vote out of the DB

### ISSUE THREAD

**Issue by paultag** [opencivicdata/pupa#181]
https://github.com/opencivicdata/pupa/pull/178 <-- let's also do an `Event.objects.get` and check the import pipeline

**Comment by jamesturk** [comment]
@paultag do you remember what you're looking for here?

**Comment by jpmckinney** [comment]
Closing for lack of clarity.

**Comment by jpmckinney** [comment]
I think maybe the issue is adding another test related to this PR: https://github.com/opencivicdata/pupa/pull/178/files
