### ISSUE TITLE
on_duplicate ignore option for duplicate documents?

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#187]
As discussed here https://github.com/opencivicdata/scrapers-us-municipal/issues/20

> In Chicago, sometimes 'Notice' and 'Agenda' are the same file. Sometimes not. Pupa doesn't allow the same file to appear more than once in document list (throws an ValueError). What's the way we want to handle this?

> @paultag said:
>
> Hurm.
>
> We have an on_duplicate="ignore" with Billy, we could implement something similar with Pupa, I guess. That or make the checking explicit or something

**Comment by jamesturk** [comment]
oh this already exists! there is an on_duplicate='ignore' flag you can pass to the add_*_link methods that'll allow this, it just has to be set explicitly to avoid unintentional errors
