### ISSUE TITLE
What's the distinction between post and role?

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#188]
Right now I'm capturing whether someone is a member, vice-chair, or chair of a committee through the "role" attribute. https://github.com/opencivicdata/scrapers-us-municipal/blob/212634b693dbbd19159a48a88e18b01599732d40/chicago/people.py#L98

This role information shows up on a person's details: http://api.opencivicdata.org/ocd-person/86a175ae-8364-4013-ab97-1c77c54a3bdc/

But not on an org's details, but posts do.

What is the semantic distinction between post and role?

**Comment by fgregg** [comment]
@jpmckinney I think this a question for you. I read http://www.popoloproject.com/specs/post.html but must admit I don't quite get this distinction.

**Comment by fgregg** [comment]
Maybe "Chairman" and "Vice Chairman" are posts, since they always exist, but regular members of committees don't have posts since the number of members can vary?

**Comment by jpmckinney** [comment]
Both Post and Membership have a `role` property. You'll almost always want to model Memberships. You may not need to model Posts though. If, for example, it's important to know when the Chair is vacant, then you'll want a Post to indicate that. A Post represents the "seat" that exists without anyone occupying it. Does that answer the question(s)?

**Comment by fgregg** [comment]
Yes. That is helpful. Thanks!
