### ISSUE TITLE
bill scrape add_action pseudo_organization

### ISSUE THREAD

**Issue by crdunwel** [opencivicdata/pupa#192]
`ValueError: cannot specify both classification and organization`

See https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/bill.py#L50 and https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/popolo.py#L183

Is this as intended? Is one only supposed to supply either an organization or a chamber? Why is the chamber then being passed as the classification argument in the pseudo_organization method?

**Comment by paultag** [comment]
Yes, this is intended.

Note it uses `organization._id`, it's not the organization name. If you give it an `organization`, then you can get classification from `organization.classification` (which it does when splatting the org out).

If you pass classification, then that means you want that one thing, which is usually a legislative chamber.

What's tripping you up here? Closing the issue.
