### ISSUE TITLE
Critical data loss issue on bill import when legislative sessions differ

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/pupa#203]
if legislative sessions differ they're deleted in the import & recreated... which cascades to bills... thus deleting all bills

how we didn't catch this before is a mystery to me :skull: 

anyone seen behavior like this @paultag @rshorey @mileswwatkins @fgregg?

**Comment by jamesturk** [comment]
just looked at other related_objects dicts on importer classes, all seem completely fine as all others are legit subobjects... legislative_sessions will have to be special cased to not be deleted in the jurisdiction importer

**Comment by jamesturk** [comment]
fixed: https://github.com/opencivicdata/pupa/compare/f9ff0d145308ab386705170556482fd3a4c4226e...master

if someone wants to review this piece before it gets merged into master that'd be great, but all tests pass including a new test for legislative_session

**Comment by mileswwatkins** [comment]
Huh, I'd never seen this behavior. Shit!

**Comment by jpmckinney** [comment]
I don't change my sessions - they are perfect as they are!
