### ISSUE TITLE
Generate Reports

### ISSUE THREAD

**Issue by mileswwatkins** [opencivicdata/pupa#204]
- Reports
  - [x] People: percentage missing [address, email, any telephone](http://www.popoloproject.com/specs/contact-detail.html#code-lists), photo
  - [x] Organizations: count by `classification` in `Jurisdiction`, total count empty
  - [x] Posts: counts for vacancies and overages
  - [x] Bills: counts for no actions, no sponsors, no versions, duplicate versions, percentage actions without types, without sponsor IDs
  - [x] Votes: percentage bad counts
  - [x] Events: (Would `Disclosure` checks go in here?)
- [x] Sorting
- [x] Filters: by `Jurisdiction`, by number of "bad" cells
- [x] Thresholds and color-coding, integer and percent formatting

**Comment by mileswwatkins** [comment]
https://github.com/opencivicdata/pupa/pull/177

**Comment by jamesturk** [comment]
👍
