### ISSUE TITLE
Django 1.9 warnings

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/pupa#210]
```
04:01:24 WARNING py.warnings: /app/.heroku/src/pupa/pupa/models.py:17: RemovedInDjango19Warning: Model class pupa.models.RunPlan doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class RunPlan(models.Model):

04:01:24 WARNING py.warnings: /app/.heroku/src/pupa/pupa/models.py:22: RemovedInDjango19Warning: Model class pupa.models.ScrapeReport doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ScrapeReport(models.Model):

04:01:24 WARNING py.warnings: /app/.heroku/src/pupa/pupa/models.py:30: RemovedInDjango19Warning: Model class pupa.models.ScrapeObjects doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ScrapeObjects(models.Model):

04:01:24 WARNING py.warnings: /app/.heroku/src/pupa/pupa/models.py:36: RemovedInDjango19Warning: Model class pupa.models.ImportObjects doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ImportObjects(models.Model):
```

Not sure of the actual cause - though I know setting `app_label` will resolve the warnings.

**Comment by jamesturk** [comment]
hm, what's your settings.py look like?  i'm not getting this error (or any error) when running w/ 1.9b1

**Comment by jpmckinney** [comment]
I'm running Django 1.8.4. Let me know if you still want my settings.py

**Comment by jamesturk** [comment]
hm, I'll try to reproduce here.  do you override INSTALLED_APPS?

**Comment by jamesturk** [comment]
also is this pupa 0.5?

**Comment by jpmckinney** [comment]
It's fc2f57f. I'll see what happens on 0.5.0.

**Comment by jamesturk** [comment]
might be safest to stay put & ignore the warnings until you're ready to,
0.5 requires 1.9 and has some bigger DB changes

**Comment by jpmckinney** [comment]
It'd be good to have changelogs for pupa, python-opencivic-data-django, python-opencivicdata-divisions, as upgrading is currently difficult.

**Comment by jpmckinney** [comment]
Also validictory.

**Comment by jamesturk** [comment]
100% agree, was planning to do this pre-0.5 but dropped that 0.5 release
for datamade guys to have something relatively stable.  I'll find some time
soon to sit down and just write

**Comment by jamesturk** [comment]
validictory has one:
http://validictory.readthedocs.org/en/latest/changelog.html  let me know if
anything is missing

**Comment by jpmckinney** [comment]
Ah, cool, I didn't look inside docs/ on GitHub.

**Comment by jpmckinney** [comment]
I needed all these in INSTALLED_APPS:

django.contrib.auth
django.contrib.contenttypes
pupa
