### ISSUE TITLE
Memberships not resolving people

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#212]
In this PR for St. Louis, https://github.com/opencivicdata/scrapers-us-municipal/pull/88. @jesseilev, is specifying committee memberships like this: 

https://github.com/opencivicdata/scrapers-us-municipal/pull/88/files#diff-c623c007907974c7c630f3c9f0258955R76

This is resulting in files like

```json
{"on_behalf_of_id": null, 
 "links": [], 
 "end_date": "", 
 "start_date": "", 
 "person_id": "~{\"name\": \"Scott Ogilvie\"}", 
 "role": "member", 
 "organization_id": "d21e4c18-9218-11e5-9e00-74f06d0d1555", 
 "label": "", 
 "extras": {}, 
 "_id": "d21e6716-9218-11e5-9e00-74f06d0d1555", 
 "post_id": null, 
 "contact_details": []}
```

However, this are not importing into the DB, and pupa is throwing an `UnresolvedError`

```python
pupa.exceptions.UnresolvedIdError: cannot resolve pseudo id to Person: ~{"name": "Scott Ogilvie"}
```

And I'm not sure why, since this seems to match what we get in the person data:

```json
{"birth_date": "", 
 "links": [], 
 "biography": "", 
 "national_identity": "", 
 "name": "Scott Ogilvie", 
 "summary": "", 
 "image": "https://www.stlouis-mo.gov/government/departments/aldermen/profiles/images/scott_ogilvie_2.jpg", 
 "other_names": [], 
 "gender": "", 
 "sources": [{"url": "https://www.stlouis-mo.gov/government/departments/aldermen/profiles/scott-ogilvie.cfm", "note": "profile"}, {"url": "https://www.stlouis-mo.gov/government/departments/aldermen/ward-24", "note": "ward"}], 
 "extras": {}, 
 "identifiers": [], 
 "death_date": "", 
 "_id": "d1fd077e-9218-11e5-9e00-74f06d0d1555", 
 "contact_details": [{"type": "voice", "value": "(314) 622-3287", "note": ""}]}
```

**Comment by fgregg** [comment]
If you run it once commenting out the adding of memberships, so people are imported into the db. You can then run the full script. The issues is that the first time you run it, the folks aren't in the database yet. This should still work if they had been previously scraped. Thoughts @jamesturk

**Comment by jamesturk** [comment]
hmmm yeah that's weird. what version of pupa is this?

any chance you can come up with a test case to reproduce this? not clear
what's different from this case to ones where it resolves just fine
