### ISSUE TITLE
[support] how to resolve to add single object created multiple times (from different sources)

### ISSUE THREAD

**Issue by patcon** [opencivicdata/pupa#215]
Hey guys, I'm stumbling against something. Toronto has multiple independent sources from which to add people -- for example, a councillor Person might be created from the official councillor page, or from a separate system that lists appointments to committees, some of which will be councillors (the latter also has record from earlier terms, whereas the former only has current term).

So it seems that if I'm adding Persons via `yield`, if i add people that are otherwise identical but differing in the `add_source` portion, they aren't resolved to the same person. I *can* get them to resolve to the same person, but I need to fudge the sources to be identical, which seems really odd.

So is this how pupa is supposed to work right now, or am I messing something up? Also, if it is how it currently works, would it be possible to change this without immense effort and breakage? Lastly, if it's not resolvable, am I right that the best work-around is to independently build a lookup system where I can lookup previous People object by name and retrieve the previous Person object for re-use? (I think I saw another scraper [EDIT: nyc + boston] doing this with a `people_d` and `committee_d` dict)

Thanks for any help!

cc: @jpmckinney

**Comment by patcon** [comment]
Update: In case you're surprised by the behaviour I was seeing, I just realized something that *may* have contributed. The name of each councillor Person had not been stripped of whitespace, even though no whitespace was showing up in the pupa database entries. I may be the case that the whitespace in the raw json _data representation was failing to match, even though it otherwise would.

Investigating now, but feel free to chime in :)

**Comment by jpmckinney** [comment]
See https://github.com/opencivicdata/scrapers-ca/pull/136#issuecomment-163468714
