### ISSUE TITLE
Resolve person_id/organization_id on event participants

### ISSUE THREAD

**Issue by patcon** [opencivicdata/pupa#217]
Unless I'm misunderstanding, pupa does not currently resolve event participants uuid's by name and type (person/org).

Would be great if someone could confirm that this isn't yet the case, and if not, I might try to sort it out. Right now, I'm just running a few manually queries to connect up events to committees :)

**Comment by fgregg** [comment]
That's correct. This is a dupe of #207

**Comment by patcon** [comment]
Heh. Oops. Rockin. Thanks @fgregg :)
