### ISSUE TITLE
Inconsistent handling of date/times

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#218]
When describing the beginning and end of a term or a bill action date, the user must use an iso format string

```python
            p.add_term('Commissioner', 'legislature', 
                       district='District {}'.format(district), 
                       start_date=start_date.isoformat(),
                       end_date=end_date)
```

When adding an event, the use needs to provide a datetime:

```
                e = Event(name=event["Name"]["label"],
                          start_time=when,
                          description=description,
                          timezone='US/Central',
                          location_name=location,
                          status=status)
```

Personally, I find this confusing. Is there any reason why we shouldn't just use a datetime.date object instead of an iso format string?

@jamesturk, @jpmckinney thoughts?

**Comment by jpmckinney** [comment]
Seems reasonable!

**Comment by jpmckinney** [comment]
For backwards compatibility, it should accepts either strings or date/time objects.

**Comment by jpmckinney** [comment]
Also, I think a reason for strings is that you can pass imprecise dates like "2014-01" or "2014"

**Comment by fgregg** [comment]
ahh.. that makes sense

**Comment by jpmckinney** [comment]
In terms of implementation, if you call `str()` on a `datetime.date`, it will come out as ISO. So, we can probably duck-type for terms and bill action dates.
