### ISSUE TITLE
Add ability to set division on bills

### ISSUE THREAD

**Issue by patcon** [opencivicdata/pupa#222]
Toronto allows agenda items to be assigned to specific wards (ie divisions):
http://app.toronto.ca/tmmis/viewPublishedReport.do?function=getAgendaReport&meetingId=10879

While it might make sense to ask for the ability to assign divisions to agenda items, it likely makes more sense to ask instead for divisions on bills (we are saving agenda items that require action/votes as bills, as that maps fairly well for Toronto). It would be useful to know which constituency a bill's vote event applies to :)

Thoughts?

**Comment by jpmckinney** [comment]
I recommend storing it under `extras`.

**Comment by patcon** [comment]
We've got ward on bills, so if it's not an official division_id anyhow, then I think that's good enough
