### ISSUE TITLE
Stop stripping leading 0's from bill identifiers

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#224]
In legislatures I scrape, it's very common to have identifies like

`Ordinance 0100`

this gets change by fix_bill_id to 

`Ordinance 100`

why? 

It's not at all clear why we we should prefer the second form.

Relevant code is https://github.com/opencivicdata/pupa/blob/master/pupa/utils/generic.py#L34 and https://github.com/opencivicdata/pupa/blob/master/pupa/importers/bills.py#L51

**Comment by fgregg** [comment]
attn @jamesturk @paultag @jpmckinney

**Comment by jpmckinney** [comment]
This came up in #151. My opinion is that Pupa shouldn't fix values in this way, and that fix_bill_id should be removed.

**Comment by fgregg** [comment]
Agree. This seems like something that should be done in the scraper, not in
the guts of the bill importer.

On Sun, Dec 27, 2015 at 11:49 AM, James McKinney <notifications@github.com>
wrote:

> This came up in #151 <https://github.com/opencivicdata/pupa/pull/151>. My
> opinion is that Pupa shouldn't fix values in this way, and that fix_bill_id
> should be removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/pupa/issues/224#issuecomment-167430760>.
>



-- 
773.888.2718

**Comment by jamesturk** [comment]
the rationale is that a lot of states are inconsistent and this lead to
dupes, normalizing fixed this, but I'd be fine with a way to disable
this/other filters on a per bill basis

**Comment by fgregg** [comment]
Why couldn't this logic be moved to the scraper? Seems cleaner then setting bill specific flags?

**Comment by jpmckinney** [comment]
Shouldn't the OpenStates scrapers just inherit from a base `OpenStatesScraper` class, to do this sort of cleanup? That's what I do in Canada.

**Comment by jamesturk** [comment]
yeah that'd work I'm sure

**Comment by jamesturk** [comment]
I think the right solution here is to implement #163 and do the work there.

**Comment by jpmckinney** [comment]
Sadly, I don't remember anything about Billy. Can you point to the relevant implementation?

**Comment by jpmckinney** [comment]
Closing in favor of #163 in any case.
