### ISSUE TITLE
Linking bill actions and events

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#225]
The legistar systems provide enough information to link bill actions to the committee or council meetings when the action took place. 

The right place to stuff this information would seem to be the `related_entities` field of bill actions. 

However, events are imported _after_ bills, so these would not resolve without some major surgery. 

If bill actions had an `extras` field I could use that store legistar's meeting GUID's and and do my resolving in my application layer (councilmatic). 

Thoughts, @jamesturk @jpmckinney, I'm very tempted to just do this with an `extras` field.

**Comment by jamesturk** [comment]
Hm, extras could work- or the resolution could take place in a final
reconciliation step, which might be the more generic solution as these
sorts of essentially circular dependencies arise.

I don't think I'd see harm in starting w/ extras though, with Open States
historically we started a few things there then once we were happy with
them graduated them to the formal definition.

**Comment by jpmckinney** [comment]
Reticketed.
