### ISSUE TITLE
If related fields are updated, the updated_at field of the parent is not updated.

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#226]
This makes it impossible to reliably find all bills that have had recently had

* changes in sponsorships
* versions
* attachments

If we removed this `if statement` https://github.com/opencivicdata/pupa/blob/master/pupa/importers/base.py#L255-L258

I think that we would have the right behaviour.

@jamesturk, @jpmckinney could you comment on the rationale for that `if statement` and removing it.

**Comment by jamesturk** [comment]
Hm, I'm not sure why that line would be the culprit.. it seems that if
statement is setting the flag to update if the key has actually changed...
the set call shouldn't do anything if it is false.

Probably worth adding a failing test for the case where you aren't seeing
updated_at update and see if removing that fixes it though, if so we can
investigate further

**Comment by jpmckinney** [comment]
+1 to creating a failing test to demonstrate the error (and then seeing if removing that line gets the test to pass).
