### ISSUE TITLE
[question] would pupa be expected to resolve organization identifiers from pseudo id?

### ISSUE THREAD

**Issue by patcon** [opencivicdata/pupa#229]
Specifically, this `from_organization`:

```py
b = Bill(
  legislative_session = '2014-2018',
  identifier = full_bill_identifier,
  title = item['title'],
  from_organization = {'identifiers': {'name': org_code}},
  )
```

Any pointers to the correct spot in the codebase would be appreciated -- I haven't dug in to much, but the object resolution code intimidates me (unrelated to code clarity or beauty, so not implying anything there :smiley:)

**Comment by fgregg** [comment]
This works for me:
https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/bills.py#L113

**Comment by patcon** [comment]
thanks @fgregg!

Hm. OK, I guess it's the extra level, and that identifiers are in another table. If I leave off the inside dict and instead just use a string (which I wouldn't have expected to work tbh), then it seems to check for my "org_code" to match against `opencivicdata_organizationidentifier.id`. What I was hoping was that the inner dict, `{'name': org_code}` would check against `opencivicdata_organizationidentifier.name`.

Anyhow, I'd still like to get this working, as getting the organization name here is not as straightforward here as getting the org_code. Any advice on where to look is appreciated, as I'll be stumbling through later :)

**Comment by fgregg** [comment]
Let's talk about this on slack
https://ocd-slack-invite-automation.herokuapp.com/

**Comment by patcon** [comment]
This might still be a valid request, but I realized I was abused `from_organization` so I think this is good to close :)
