### ISSUE TITLE
Add easy-release task

### ISSUE THREAD

**Issue by patcon** [opencivicdata/pupa#234]
I'm used to using one-liner release tools in other languages, and #228 made me wonder whether python has an equivalent. Best when release is as tiny a hassle as humanly possible, then we all :heart: releasing more :)

Turns out it does: https://pypi.python.org/pypi/zest.releaser

I like learning the landscape in other languages, so happy to put this together!

cc: @jamesturk

**Comment by jamesturk** [comment]
I'd prefer to stick to language-standard tools  until there's a
demonstrated need for this.

Right now a release requires someone to manually update the changelog,
which I find preferable to automatically generated changelogs the same way
human-written documentation is generally stronger than the automagically
generated variety.

**Comment by paultag** [comment]
Yeah this seems to be a bit overkill to my eye, anyway

**Comment by patcon** [comment]
Ok, that's ok too :) Just got the sense that you wanted to confirm we needed a release, and thought we could get things set up so that that wasn't on your radar, and every change essentially gets one
