### ISSUE TITLE
Add extras field to EventAgendaItem

### ISSUE THREAD

**Issue by patcon** [opencivicdata/pupa#237]
As discussed here, Toronto has timestamp data for individual agenda items:
https://github.com/opencivicdata/scrapers-ca/issues/163#issuecomment-208717298

My thoughts is that this would fix best into an extras field on agenda items. In the meantime, I could put it in Event extras, but that doesn't seem ideal.

Thoughts?

cc: @jpmckinney

**Comment by jpmckinney** [comment]
Is there no extras field on agenda items?

**Comment by patcon** [comment]
Nope, not seeing it in the db table

**Comment by jpmckinney** [comment]
I suppose that's the only place to put it then.

**Comment by jpmckinney** [comment]
Reticketed.
