### ISSUE TITLE
body member cannot occupy both a membership post and a leadership post

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#244]
Relates to https://github.com/popolo-project/popolo-spec/issues/125

I need to keep track of the posts that make a member part of a body and any leadership posts they have in the body (like "speaker"). This now seems impossible with pupa's duplicate checking.

```python
pupa.exceptions.DuplicateItemError: attempt to import data that would conflict with data already in the import: 
{'role': '1st Vice Chair', 'post_id': None, 'on_behalf_of_id': None, 
  'start_date': '2014-07-01', 'person_id': 'ocd-person/c976773c-c13e-485c-bbd6-0a007970f029', 
  'label': '', 'end_date': '2015-06-30', 
  'organization_id': 'ocd-organization/42e23f04-de78-436a-bec5-ab240c1b977c', 'extras': {}} 
(already imported as Mark Ridley-Thomas in Board of Directors (Board Member))
```

Do we want to change how we do do duplicate checking? Attn @jamesturk @jpmckinney

**Comment by jpmckinney** [comment]
Sounds good to me. I can't see a consequence of adding 'role' to the uniqueness test for memberships.

**Comment by fgregg** [comment]
nevermind, had out of date version of pupa on the server. sorry for the line noise
