### ISSUE TITLE
related_entities argument to Bill.add_action()

### ISSUE THREAD

**Issue by divergentdave** [opencivicdata/pupa#266]
I'm working on migrating a scraper from Billy to Pupa (over at openstates/openstates#1411) and I was looking for a cognate to the `committees` argument to `add_action()`. It seems like the argument I'm looking for would be `related_entities`, but the value passed in that argument always gets discarded. See https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/bill.py#L51. I figure the value should be passed on to the `Action` constructor, possibly after passing it through `cleanup_list()`. Thoughts?

**Comment by fgregg** [comment]
Here's how we do it on existing pupa scrapers https://github.com/opencivicdata/scrapers-us-municipal/blob/master/lametro/bills.py#L116-L123

**Comment by divergentdave** [comment]
Ah, OK thanks.
