### ISSUE TITLE
Distinct vote events, despite same motion, org, and date

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#274]
From time to time it happens in the Illinois legislature that a motion will be brought forward for a vote, it will fail, and then it will be brought back again on the same day for a revote.

For example http://ilga.gov/legislation/votehistory.asp?DocNum=2963&DocTypeID=HB&LegID=104486&GAID=14&SessionID=91&GA=100&SpecSess=

The `pupa` vote importer complains that these votes are dupes. Thoughts on how to not have that happen.

**Comment by estaub** [comment]
Not sure if this is helpful... there often are other correlation ids in the input that you wouldn't want to be brought forward, but may be useful just for dupe-checking.  For instance, in this case, the URLs of the PDFs are different.  Of course, they could still be referring to the same real-world vote.

**Comment by fgregg** [comment]
This is true @estaub, if the vote object has an `identifier` defined, then the importer will use that to check for uniqueness. We could use the pdf as the identifier, but it seems like practice has been for `identifier` to be something semantically meaningful (for bills `identifier` is often the id that the legislature uses to refer to the bill)

**Comment by jamesturk** [comment]
Agh, I know we discussed this somewhere, I guess unfortunately not on the ticket. 

Do you recall the options we discussed? 

I remember we talked about using the total vote tally, but two unanimous votes would still not really stand out there.  What do you think IL has that we can differentiate on?

**Comment by estaub** [comment]
@jamesturk In the example, the pdfs for each vote has a different url (of course, they would have to be different!).  If there's an unpublished (not in API) field for scrapers to use for input correlation IDs, that would do it.  

Also, the vote results are different.  That can't be relied on, but will detect most, and I doubt many folks would care that votes that have exactly the same outcome, on the same motion, on the same day, are mistakenly coalesced.

**Comment by fgregg** [comment]
I really like @estaub's idea of "unpublished" identifier. This would actually be very useful for some problems we are having with events where the time is revised (but the listing url of the event stays the same).

**Comment by jamesturk** [comment]
I think that'd make sense, and of course URL would be one option but I
think we should leave open others too.

This is probably pupa-specific, not an OCD spec thing as it is more of an
implementation detail.  Do you want to shoot for a PR that optionally uses
it to disambiguate if present.  Presumably if it is present it supersedes
other matching? (which would be handy if you for sure had a strong
identifier for something).

**Comment by fgregg** [comment]
>  Do you want to shoot for a PR that optionally uses it to disambiguate if present. Presumably if it is present it supersedes other matching? 

Yes and yes! I may not have time for this for a week or so, so if anyone else wants to claim it, that'd be great.

**Comment by fgregg** [comment]
Okay, I'm ready to pick this up. I'm going to start by storing the an identifier in the `extras` field. 

This doesn't quite feel like the right solution, but it really don't feel like the right solution to have an pupa specific attribute be part of the ocd models.

Maybe the right thing would be for pupa to add an _identifier field to the models? Any thoughts on this?

**Comment by jamesturk** [comment]
Can you clarify what you mean by the last line?  I'm not sure I follow
