### ISSUE TITLE
do we need to match memberships on label & role?

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/pupa#275]
taking a closer look at this commit: https://github.com/opencivicdata/pupa/commit/3e11d355f8601eb255dba4dc45774cb9ab65600b

looking at the example in the test- we could have just matched on label & the two roles still would have resolved, so @fgregg can you elaborate on why you added 

```
                'role' : membership['role'],
```

and if it'd break things to remove?

**Comment by jamesturk** [comment]
#276 removes the offending line & tests pass.  this restores the behavior of primary_org

**Comment by jamesturk** [comment]
actually scratch this being the cause of the OS breakage, that seems to be something else in how we handle memberships, but we should still take a closer look at this since the line added & the test don't seem to be related.  we either need to tighten the test or reconsider the line

**Comment by jpmckinney** [comment]
Linking to PR which explains what having `role` in spec was about: https://github.com/opencivicdata/pupa/pull/245 I think the issue in the test is that `label` should/could have been left blank. Since `label` is set (and is different), the test passes regardless of the values for `role`.

**Comment by jamesturk** [comment]
gotcha,  we should make sure we fix the test to actually check for that case, closed #276

**Comment by jamesturk** [comment]
just tried to fix this test and even w/o label the test passes without the change

https://github.com/opencivicdata/pupa/compare/master...bugfix-275

maybe @fgregg can weigh in when he has a chance

**Comment by fgregg** [comment]
This is because it has been my practice to not set `label`, which seems optional, but only set `role`, which seems required.

If label is not set, then it's necessary to use role to distinguish memberships in order for person to hold more than one post in the same legislature.

**Comment by jamesturk** [comment]
I'm alright with the idea but I was thinking​ theres an issue in what we're
testing as the addition of the line in the import isn't necessary to get
the new test to pass. Or maybe I'm misunderstanding & they aren't directly
related.

**Comment by fgregg** [comment]
agree. the test should have not have label set.

**Comment by jamesturk** [comment]
I tried that here: https://github.com/opencivicdata/pupa/compare/master...bugfix-275 & still passing, not urgent but it could probably use some attention at some point
