### ISSUE TITLE
Don't break when session is started with no bills yet

### ISSUE THREAD

**Issue by estaub** [opencivicdata/pupa#300]
The scraper base code an exception if a scrape comes up with zilch, but most/all individual OpenStates state scrapers throw when a session is seen that's not represented in their `__init__.py`.  This presents a catch-22 when a state has staged their next session, but there are no bills yet.  The current case of this is Oklahoma.  It's blowing up right now on undefined new sessions, but once that's fixed the bill scrape will be empty.

The current solution in common use, afaik, is to simply disable the bill scraper and then do another code change when bills are present.

I'd like to come up with a systematic way of dealing with this.  My best thought so far is to add an "ok_if_empty" option to the base scraper, and have state scrapers set this for sessions that have a non-null start_date in the future or very recent past ("recent" settable, defaulting to one week back).

If that makes sense, where should that check-session-date-and-set-scraper-option code live?  There's currently no "BillScraper" base-class or mixin; should I create one, and if so, which?  Or, just create a helper module?  I have a feeling that a base-class or mixin will get a lot more use; I'm surprised there hasn't been need already - is there bad experience with going that way?

**Comment by showerst** [comment]
One thing to point out is that the relation between actual session start dates and when the states start populating site data is pretty tenuous. Between prefiles and session-start lag there's often data weeks early, or no data weeks late.

This sounds like it fits in pupa as either a setting or an env variable, to turn off the errors on empty sessions if that is set. Here's the check you'd need to disable, in [base.py](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/base.py#L120)

That would also let you apply it to any scrape, not just for bills, which would come in handy when legislators aren't posted yet.

**Comment by jamesturk** [comment]
I'm torn on this, it is a recurring annoyance, but it was intentionally designed that way going back to the original billy version of this feature from ~6 years ago.

It is really easy to turn on a flag that says "--allow-none" or whatever, but when would it get turned off?  

At least with turning off the bill scrape entirely, there's a necessary reason to turn it back on.  I'm inclined to stick w/ what we have, with the recommended behavior staying as-is, namely "don't run scrapers where you know you aren't getting data".
