### ISSUE TITLE
Allow `Post` scraper and importer to set `maximum_memberships` for multi-member districts

### ISSUE THREAD

**Issue by mileswwatkins** [opencivicdata/pupa#311]
Right now, any `Post` created by Pupa will have the default number of `maximum_memberships`: one. There are many cases where this is inaccurate, and the Py-OCD support is already present; it'd be great to have Pupa support this.

cc https://github.com/openstates/openstates/issues/2208

**Comment by jamesturk** [comment]
fixed in master
