### ISSUE TITLE
Allow event location to be null

### ISSUE THREAD

**Issue by hancush** [opencivicdata/pupa#312]
Hi there! 

There are some cases where an event is created with a time and date, but the location is TBD. 

The [OCD standard](http://opencivicdata.readthedocs.io/en/latest/data/event.html) is slightly ambiguous on whether an Event can have no location (allowing for null, but labeling location a required field):

> **location (object, null)**
  Where the event will take place. (required)

If null is acceptable, though, it would be great if this were reflected in the `pupa.scrape` event location schema.

https://github.com/opencivicdata/pupa/blob/c0dbe820821caa66f1cb02675dfdcd3df22307b7/pupa/scrape/schemas/event.py#L43-L47 

Thanks for all you do!

**Comment by fgregg** [comment]
To chime in here, if this change was acceptable to @jamesturk and others, we'd be happy to make the PR.

**Comment by jamesturk** [comment]
Seems fine to me :)

**Comment by hancush** [comment]
Added in #334 and #335.
