### ISSUE TITLE
let scraper set date of an eventdocument and eventmedia 

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#324]
EventDocument and EventMedia both have `date` attributes.

I'm not sure what the intent of that attribute is, but it would be convenient for me to use it store the publication date of the the document and media.

However, the relevant methods on the event scraper do not have an argument for setting the date.

https://github.com/opencivicdata/pupa/blob/fd599b7fa82059f2ef94bce432dada193bbfdd6c/pupa/scrape/event.py#L123-L130

@jamesturk, is this by design? If not, I'll make a PR adjusting these methods.

**Comment by jamesturk** [comment]
PR would be great, we pretty much stopped using event stuff, so anything
you want to do is fine with me
