### ISSUE TITLE
pupa init doesn't automagically add division_id (just jurisdiction_id)

### ISSUE THREAD

**Issue by paultag** [opencivicdata/pupa#93]
Old bit that we changed a little, since we want to automate the creation of the JID via classification and division ID. Related to #91 #92

**Comment by xpat** [comment]
The command "pupa init seattle" just yielded this error message:

16:02:49 CRITICAL pupa: Unable to import Jurisdiction subclass from seattle. Jurisdiction subclass may be missing a division_id and classification


# encoding=utf-8
from pupa.scrape import Jurisdiction
from .people import SeattlePersonScraper

class Seattle(Jurisdiction):
    jurisdiction_id = "ocd-division/country:us/state:wa/place:seattle/council"
    division_id = "ocd-division/country:us/state:wa/place:seattle/council"
    name = "Seattle City Council"
    url = "http://seattle.gov/council/"
    scrapers = {
        "people": SeattlePersonScraper,
    }

    def get_organizations(self):
        return []
